config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @posts = Post.all
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js 
        #format.js 
      else
        format.html { render :new }
        format.js { render json: @post.errors.full_messages, status: :unprocessable_entity} 
        
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title TodoAjax
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true 
    = javascript_include_tag 'application', 'data-turbolinks-track': true 
    = csrf_meta_tags

  body
    nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          button.navbar-toggle data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="/" ToDo Sample App
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-right
            li
              =link_to 'Sign In', root_path
            li
              =link_to 'Register', root_path
      
    = yield

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.slim
.col-md-4.panel
  .panel-heading
    h1 =post.title
  .panel-body
    p =post.content
  .panel-footer
    =link_to 'Destroy', post, data:{confirm:"Are you sure?"}, method: :delete, class: 'btn btn-danger' 

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.slim
.container
  .row
    .text-center
      button type='button' class='btn btn-primary btn-lg' data-toggle='modal' data-target='#my_modal' New Post
  #my_counter=@posts.count
  .row
    .text-center#my_posts
      =render @posts
/ Modal
.modal.fade#my_modal
  .modal-dialog
    .modal-content
      .modal-header
        This is modal header
      .modal-body
        =simple_form_for(@post, remote: true) do |f|
          =f.input :title, class: 'post_title'
          =f.input :content, class: 'post_content'
          =f.submit class: 'btn btn-success'
      .modal-footer
        button type='button' class='btn btn-default' data-dismiss='modal' Close
      /<div class="modal-content">
        /<div class="modal-header">
          /<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          /<h4 class="modal-title">Modal title</h4>
        /</div>
        /<div class="modal-body">
          /<p>One fine body&hellip;</p>
        /</div>
        /<div class="modal-footer">
          /<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          /<button type="button" class="btn btn-primary">Save changes</button>
        /</div>
      /</div><!-- /.modal-content -->
    /</div><!-- /.modal-dialog -->
  /</div><!-- /.modal -->

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>